name: docker

on:
  push:
    branches:
      - master
      - dev-1.x
      - github-actions
      - ci
      - docker
  pull_request:
    branches:
      - master

jobs:
  test_docker_generic:
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    name: PHP ${{ matrix.php-versions }} / ${{ matrix.docker-image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-image:
          - "alpine"
          - "debian"
        php-versions:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - uses: actions/checkout@v2
      - run: bash .github/scripts/docker.sh
        env:
          PHP_VERSION: ${{ matrix.php-versions }}
          DOCKER_NAME: ${{ matrix.docker-image }}

  test_docker_fedora:
    name: fedora
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash .github/scripts/docker.sh
        env:
          DOCKER_NAME: fedora
          TEST_PHP_EXECUTABLE: /usr/bin/php
