name: linux

on:
  push:
    branches:
      - master
      - dev-1.x
      - github-actions
      - ci
      - linux
  pull_request:
    branches:
      - master

jobs:
  test_linux:
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    name: PHP ${{ matrix.php-versions }} / ${{ matrix.operating-system }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04]
        php-versions:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        coverage:
          - "true"
          - "false"

    steps:
      - uses: actions/checkout@v2

      - run: bash .github/scripts/linux.sh
        env:
          PHP_VERSION: ${{ matrix.php-versions }}
          COVERAGE: ${{ matrix.coverage }}

      - name: Coveralls
        if: ${{ matrix.coverage == 'true' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.info
