name: osx

on:
  push:
    branches:
      - master
      - dev-1.x
      - github-actions
      - ci
      - osx
      - "2.x"
  pull_request:
    branches:
      - master

jobs:
  test_osx:
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    name: PHP ${{ matrix.php-versions }} / ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - "macos-latest"
        php-versions:
          - "8.0"
    steps:
      - uses: actions/checkout@v2
      - run: bash .github/scripts/osx.sh
        env:
          PHP_VERSION: ${{ matrix.php-versions }}
